import Head from 'next/head'
// import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Comic } from './components/Comic';
import Static from './api/Static.json';



export default function Home() {
  return (
    <>
      <Head>
        <title>Exercise 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.slides} style={{display:'grid', gap: 30 + 'px', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', padding: 50 + 'px'}}>
        {Static.map(comic => 
          <Comic
          key={comic.id}
          title={comic.title}
          issueNumber={comic.issueNumber}
          publishDate={comic.publishDate}
          creators={comic.creators}
          thumbnail={comic.thumbnail}
          />
        )}
      </main>
    </>
  )
}

