import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Comic } from './components/Comic';
import  useMarvelApi  from './api/useMarvelApi';
const md5 = require('md5');

export async function getStaticProps(){
  const timestamp = Date.now();
  const hash = md5(timestamp + process.env.NEXT_PUBLIC_PRIVATE_API_KEY + process.env.NEXT_PUBLIC_API_KEY)
  
  let API_URL = `https://gateway.marvel.com/v1/public/comics?ts=${timestamp}&apikey=${process.env.NEXT_PUBLIC_API_KEY}&hash=${hash}`
    return { props: {API_URL}}
}

export default function Home({ API_URL }) {
  const { isLoading, isError, apiData } = useMarvelApi(API_URL);

  return (
    <>
      <Head>
        <title>Exercise 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading && <h2>Loading Comics...</h2>}
      {isError && !isLoading && <h2>Error Loading Comics</h2>}

      {!isLoading && !isError && apiData && 
        <main className={styles.slides} style={{display:'grid', gap: 30 + 'px', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', padding: 50 + 'px'}}>
        
        {apiData.map(comic => 

          <Comic
          key={comic.id}
          title={comic.title}
          issueNumber={comic.issueNumber}
          publishDate={comic.publishDate}
          creators={comic.creators.items.length > 0 ? comic.creators.items : null}
          thumbnail={`${comic.thumbnail.path}.${comic.thumbnail.extension}`}
          />

        )} 

      </main>}

    </>
  )
}

